# Generated by Django 5.1.4 on 2025-01-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="data")),
                ("accesspwd", models.CharField(max_length=255)),
                ("deletionpwd", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
